"""create table rss_fwd_record

Revision ID: 981aec5a86cb
Revises: 
Create Date: 2025-01-12 00:23:19.262195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '981aec5a86cb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ('rss_fwd',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rss_fwd_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('guid', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_guid', 'rss_fwd_record', ['task_id', 'guid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_task_guid', table_name='rss_fwd_record')
    op.drop_table('rss_fwd_record')
    # ### end Alembic commands ###
